# Generated by Django 5.1.3 on 2024-12-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_name', models.CharField(max_length=25)),
                ('license_plate', models.CharField(max_length=15)),
                ('driver_name', models.CharField(max_length=50)),
                ('passenger_capacity', models.IntegerField()),
                ('car_model', models.CharField(max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
